/** Compact TUI rendering helpers for pi-yt tools. */
import {
  createToolArtifactOutputSection,
  formatToolCallLine,
  joinCallSegments,
  summarizeItemList,
  summarizeOneLine,
  ToolCallComponent,
  type ToolCallTheme,
  ToolResultComponent,
  type ToolResultContent,
  type ToolResultTheme,
  withToolName,
} from "pi-extension-kit/tool-chrome";
import { isYtTranscriptDetails } from "./artifacts";
import type { YtTranscriptParams, YtTranscriptToolDetails } from "./contracts";

export interface YtCallRenderOptions {
  name: string;
  url?: string;
  languages?: readonly string[];
  sourcePreference?: string;
  placeholder?: string;
}

export function formatYtToolCall(
  theme: ToolCallTheme,
  options: YtCallRenderOptions
): string {
  return formatToolCallLine(options.name, theme, {
    detail: joinCallSegments(...buildYtToolCallSummary(options)),
    placeholder: options.placeholder,
  });
}

export function renderYtToolCall(
  theme: ToolCallTheme,
  context: { lastComponent?: unknown; argsComplete?: boolean },
  options: YtCallRenderOptions
): ToolCallComponent {
  return new ToolCallComponent({
    context: withToolName(context, options.name),
    theme,
    summary: buildYtToolCallSegments(options),
    pending: options.placeholder,
    empty: options.placeholder,
  });
}

export function renderYtTranscriptCall(
  args: Partial<YtTranscriptParams> | undefined,
  theme: ToolCallTheme,
  context: { lastComponent?: unknown; argsComplete?: boolean }
): ToolCallComponent {
  return renderYtToolCall(theme, context, {
    name: "yt_transcript",
    url: args?.url,
    languages: args?.languages,
    sourcePreference: args?.sourcePreference,
    placeholder: "...",
  });
}

export function renderYtTranscriptResult(
  result:
    | {
        details?: unknown;
        content?: readonly { type: string; text?: string }[];
      }
    | undefined,
  renderOptions: { expanded?: boolean; isPartial?: boolean },
  theme: ToolResultTheme,
  context: { lastComponent?: unknown; isError?: boolean }
): ToolResultComponent {
  const details = isYtTranscriptDetails(result?.details)
    ? result.details
    : undefined;

  return new ToolResultComponent({
    context,
    theme,
    options: renderOptions,
    result,
    view: buildYtTranscriptResultView(details),
  });
}

function buildYtTranscriptResultView(
  details: YtTranscriptToolDetails | undefined
) {
  if (!details) {
    return {
      partial: "Fetching transcript...",
      empty: "No transcript metadata returned.",
    };
  }

  if (details.status === "generated") {
    const summary = `generated by ${details.provider}/${details.model}`;
    const artifactSection = createToolArtifactOutputSection(details.artifacts, {
      collapsed: "all",
    });
    return {
      partial: "Fetching transcript...",
      collapsed: {
        text: details.title ? `${summary} · ${details.title}` : summary,
        color: "warning" as const,
        mode: "truncate" as const,
      },
      expanded: [
        details.title
          ? { text: `title: ${details.title}`, mode: "truncate" as const }
          : undefined,
        {
          text: summary,
          color: "warning" as const,
          mode: "truncate" as const,
        },
        ...details.warnings.map((warning) => ({
          text: `warning: ${warning}`,
          color: "warning" as const,
          mode: "wrap" as const,
        })),
        artifactSection,
      ].filter(isDefined),
      raw: artifactSection,
    };
  }

  if (details.status === "no_subtitles") {
    return {
      partial: "Fetching transcript...",
      collapsed: {
        text: `no subtitles for ${details.requestedLanguages.join(", ")}`,
        color: "warning" as const,
        mode: "truncate" as const,
      },
      expanded: [
        details.title
          ? { text: `title: ${details.title}`, mode: "truncate" as const }
          : undefined,
        {
          text: `requested: ${details.requestedLanguages.join(", ")}`,
          color: "muted" as const,
          mode: "truncate" as const,
        },
        {
          text: `manual: ${formatLanguages(details.availableManualLanguages)}`,
          color: "muted" as const,
          mode: "truncate" as const,
        },
        {
          text: `auto: ${formatLanguages(details.availableAutoLanguages)}`,
          color: "muted" as const,
          mode: "truncate" as const,
        },
        ...details.warnings.map((warning) => ({
          text: `warning: ${warning}`,
          color: "warning" as const,
          mode: "wrap" as const,
        })),
      ].filter(isDefined),
    };
  }

  const summary = `${details.selectedLanguage}/${details.subtitleSource}: ${details.cleanSegmentCount} clean segments (${details.segmentCount} raw)`;
  const artifactSection = createToolArtifactOutputSection(details.artifacts, {
    collapsed: "all",
  });
  const expanded: ToolResultContent = [
    details.title
      ? { text: `title: ${details.title}`, mode: "truncate" as const }
      : undefined,
    {
      text: summary,
      color: "success" as const,
      mode: "truncate" as const,
    },
    ...details.warnings.map((warning) => ({
      text: `warning: ${warning}`,
      color: "warning" as const,
      mode: "wrap" as const,
    })),
    artifactSection,
  ].filter(isDefined);

  return {
    partial: "Fetching transcript...",
    collapsed: {
      text: details.title ? `${summary} · ${details.title}` : summary,
      mode: "truncate" as const,
    },
    expanded,
    raw: artifactSection,
  };
}

function buildYtToolCallSegments(options: YtCallRenderOptions): Array<{
  text: string;
  color: "accent" | "muted" | "dim";
}> {
  const [url, languages, sourcePreference] = buildYtToolCallSummary(options);
  return [
    url ? { text: url, color: "accent" as const } : undefined,
    languages ? { text: languages, color: "muted" as const } : undefined,
    sourcePreference
      ? { text: sourcePreference, color: "dim" as const }
      : undefined,
  ].filter(isDefined);
}

function buildYtToolCallSummary(
  options: YtCallRenderOptions
): [string | undefined, string | undefined, string | undefined] {
  return [
    summarizeOneLine(options.url, 90),
    summarizeItemList(options.languages ? [...options.languages] : undefined, {
      maxItems: 4,
      separator: ",",
    }),
    summarizeOneLine(options.sourcePreference, 30),
  ];
}

function formatLanguages(languages: readonly string[]): string {
  return languages.length === 0 ? "none" : languages.join(", ");
}

function isDefined<T>(value: T | undefined): value is T {
  return value !== undefined;
}
