import { expect, test } from "bun:test";
import type { YtTranscriptToolDetails } from "./contracts";
import {
  formatYtToolCall,
  renderYtToolCall,
  renderYtTranscriptResult,
} from "./rendering";

const plainTheme = {
  bold: (text: string) => text,
  fg: (_color: string, text: string) => text,
};

test("formats compact yt_transcript calls", () => {
  expect(
    formatYtToolCall(plainTheme, {
      name: "yt_transcript",
      url: "https://www.youtube.com/watch?v=abc123",
      languages: ["en", "es"],
      sourcePreference: "manual_then_auto",
    })
  ).toBe(
    "yt_transcript https://www.youtube.com/watch?v=abc123 · en,es · manual_then_auto"
  );
});

test("collapsed call rendering stays concise", () => {
  const component = renderYtToolCall(
    plainTheme,
    {},
    {
      name: "yt_transcript",
      url: "https://example.com/video",
    }
  );
  expect(component.render(80)[0]?.trimEnd()).toBe(
    "yt_transcript https://example.com/video"
  );
});

test("renders success results with artifacts in expanded view", () => {
  const details: YtTranscriptToolDetails = {
    status: "success",
    title: "Fixture Video",
    originalUrl: "https://example.com/video",
    webpageUrl: "https://example.com/video",
    videoId: "abc",
    duration: 10,
    requestedLanguages: ["en"],
    selectedLanguage: "en",
    subtitleSource: "manual",
    segmentCount: 4,
    cleanSegmentCount: 2,
    cleaning: {
      rawSegmentCount: 4,
      cleanedSegmentCount: 2,
      exactDuplicateMerges: 0,
      progressiveDuplicateMerges: 1,
      overlapMerges: 1,
      readableChunkMerges: 0,
      heuristic: true,
      warnings: ["minor warning"],
    },
    previewText: "Hello",
    previewTruncated: false,
    warnings: ["minor warning"],
    artifacts: [
      {
        key: "cleanTranscriptText",
        label: "clean transcript",
        kind: "file",
        path: "/tmp/pi-yt/transcript.clean.txt",
        primary: true,
      },
      {
        key: "cleanTranscriptJson",
        label: "clean transcript JSON",
        kind: "file",
        path: "/tmp/pi-yt/transcript.clean.json",
      },
      {
        key: "transcriptText",
        label: "raw transcript",
        kind: "file",
        path: "/tmp/pi-yt/transcript.txt",
      },
      {
        key: "transcriptJson",
        label: "raw transcript JSON",
        kind: "file",
        path: "/tmp/pi-yt/transcript.json",
      },
      {
        key: "rawSubtitle",
        label: "raw subtitle",
        kind: "file",
        path: "/tmp/pi-yt/en.vtt",
      },
      {
        key: "metadata",
        label: "metadata",
        kind: "file",
        path: "/tmp/pi-yt/metadata.json",
      },
    ],
  };

  const collapsed = renderYtTranscriptResult(
    { details },
    { expanded: false },
    plainTheme,
    {}
  )
    .render(100)
    .map((line) => line.trimEnd());
  const expanded = renderYtTranscriptResult(
    { details },
    { expanded: true },
    plainTheme,
    {}
  )
    .render(100)
    .map((line) => line.trimEnd());

  expect(collapsed).toEqual([
    "en/manual: 2 clean segments (4 raw) · Fixture Video",
  ]);
  expect(expanded).toContain("title: Fixture Video");
  expect(expanded).toContain("warning: minor warning");
  expect(expanded).toContain(
    "clean transcript: /tmp/pi-yt/transcript.clean.txt"
  );
  expect(expanded).toContain("raw transcript: /tmp/pi-yt/transcript.txt");
});

test("renders generated Gemini transcripts as a warning-quality result", () => {
  const generated: YtTranscriptToolDetails = {
    status: "generated",
    title: "Fallback Fixture",
    originalUrl: "https://www.youtube.com/watch?v=abc",
    videoId: "abc",
    requestedLanguages: ["en"],
    provider: "gemini",
    model: "gemini-test",
    previewText: "Generated speech",
    previewTruncated: false,
    warnings: ["AI-generated transcript"],
    artifacts: [
      {
        key: "generatedTranscriptText",
        label: "Gemini transcript",
        kind: "file",
        path: "/tmp/pi-yt/transcript.gemini.md",
        primary: true,
      },
    ],
  };

  const collapsed = renderYtTranscriptResult(
    { details: generated },
    { expanded: false },
    plainTheme,
    {}
  ).render(100)[0];
  const expanded = renderYtTranscriptResult(
    { details: generated },
    { expanded: true },
    plainTheme,
    {}
  )
    .render(100)
    .map((line) => line.trimEnd());

  expect(collapsed?.trimEnd()).toBe(
    "generated by gemini/gemini-test · Fallback Fixture"
  );
  expect(expanded).toContain("warning: AI-generated transcript");
  expect(expanded).toContain(
    "Gemini transcript: /tmp/pi-yt/transcript.gemini.md"
  );
});

test("renders no-subtitle and missing-detail states compactly", () => {
  const noSubtitle: YtTranscriptToolDetails = {
    status: "no_subtitles",
    originalUrl: "https://example.com/video",
    title: "No French",
    videoId: "abc",
    requestedLanguages: ["fr"],
    availableManualLanguages: ["en"],
    availableAutoLanguages: [],
    warnings: ["No matching subtitles."],
  };

  expect(
    renderYtTranscriptResult({ details: noSubtitle }, {}, plainTheme, {})
      .render(80)[0]
      ?.trimEnd()
  ).toBe("no subtitles for fr");
  expect(
    renderYtTranscriptResult(undefined, {}, plainTheme, {})
      .render(80)[0]
      ?.trimEnd()
  ).toBe("No transcript metadata returned.");
});
